### ISSUE TITLE
[COL] After update to .40

### ISSUE THREAD

**Issue by drakray** [MinecraftModDevelopment/AdditionalLootTables#14]
https://pastebin.com/LLFsKYVq
```
net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Additional Loot Tables (alt)
Caused by: java.lang.UnsupportedOperationException
	at com.sun.nio.zipfs.ZipPath.toFile(ZipPath.java:597)
	at com.mcmoddev.alt.api.PluginLoader.lambda$loadResources$0(PluginLoader.java:127)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source)
	at java.util.stream.ReferencePipeline$Head.forEach(Unknown Source)
	at com.mcmoddev.alt.api.PluginLoader.loadResources(PluginLoader.java:87)
	at com.mcmoddev.alt.AdditionalLootTables.init(AdditionalLootTables.java:69)
```

**Comment by dshadowwolf** [comment]
Well, sh... <self censors>oot - okay, I've been seeing something similar crop up over in [MMD OreSpawn](http://github.com/MinecraftModDevelopmentMods/OreSpawn) so... soon as I get my head out of some work I've been doing on a feature for *Metals, I'll get to this. I think its something with a change to how the FileSystem stuff works.

**Comment by brisingraerowing** [comment]
Was this supposed to be fixed in .42? It still breaks on the same line. Apparently ZipPath can't be converted to a file. You might try the solution [here](https://stackoverflow.com/questions/41979509/how-to-convert-a-zippath-to-file).

**Comment by jriwanek** [comment]
Unfortunately build 42 heading to curse was a screwup on my part, (thanks autopushing), dshad is still working on it.

**Comment by R0gu3P403n1x** [comment]
Was going to start a new thread, but this seems to be the issue exactly...  ALT .40+ seems to work fine for me until I add in Base Metals.  The Base Metals revision doesn't seem to mater.  Base Metals runs fine without ALT as well.  Reverting to .39 lets everything work fine except MMD Buckets, but I suspect that is just because it hasn't been updated as recently.  Hope this information is helpful.

**Comment by jriwanek** [comment]
Very, thank you very much!
